### PR TITLE
Fixed destroy process of a single editor instance working within Context

### LINKED ISSUE #354: Can't destroy the editor within a context
## Steps to reproduce

1.  Download the example project - [react-context-destroy-issue.zip](https://github.com/ckeditor/ckeditor5-react/files/10332280/react-context-destroy-issue.zip).
2.  Unzip, run `npm install && npm run build`.
3.  Open `samples/real-time-collaboration-for-react.html`.
4.  Click on the _Show/hidden CKE_ button.

## Actual result

The editor instance is not destroyed.

## Expected result

The editor instance is destroyed.

## Notes

It's a regression introduced in v5.0.5.

### PR DESCRIPTION
**Pull request by Mgsy**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed destroy process of a single editor instance working within Context. Closes #354.

### CODE REVIEW

File: src/ckeditor.jsx [hunk 1]
```diff
@@ -145,6 +145,7 @@ export default class CKEditor extends React.Component {
 	async _initializeEditor() {
 		await this.editorDestructionInProgress;
 
+		/* istanbul ignore next */
 		if ( this.watchdog ) {
 			return;
 		}
```
Comment (psmyrek) [inline src/ckeditor.jsx:151]: It seems that this condition is no longer necessary. It was added while we were working on double rendering issue. But I leave it just in case.

File: src/ckeditor.jsx [hunk 2]
```diff
@@ -230,16 +231,23 @@ export default class CKEditor extends React.Component {
...
+						resolve();
+					} );
+				} else {
 					resolve();
-				} );
-			} else {
-				resolve();
-			}
+				}
+			} );
```
Comment (psmyrek) [inline src/ckeditor.jsx:250]: No idea how to get rid of this `setTimeout()`, as the `<CKEditor />` does not know if `<CKEditorContex />` is going to destroy the editor.

Let's keep it as it is.

File: src/ckeditor.jsx [hunk 3]
```diff
@@ -348,9 +356,20 @@ class EditorWatchdogAdapter {
...
+		// Otherwise, it causes that the editor is destroyed twice. However, there is a case, when the editor
+		// needs to be removed from the context, without destroying the context itself. We may assume the following
+		// relations with `ContextWatchdog#state`:
+		//
+		// a) `ContextWatchdog#state` === 'ready' - context is not destroyed; it's safe to destroy the editor manually.
+		// b) `ContextWatchdog#state` === 'destroyed' - context is destroyed; let `ContextWatchdog` handle the whole process.
+		//
+		// See #354 for more information.
+		if ( this._contextWatchdog.state === 'ready' ) {
+			return this._contextWatchdog.remove( this._id );
```
Comment (psmyrek) [inline src/ckeditor.jsx:370]: The `this._contextWatchdog.remove()` returns a promise, as expected.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Comment by Aerophite** [comment]
This appears to have fixed #351 as well
