### PR TITLE
Integration with `MultiRootEditor`

### LINKED ISSUE #257: Add support for the multi-root editor
Currently, the integration with the multi-root editor doesn't work out of the box, so we should introduce support for it.

### PR DESCRIPTION
**Pull request by DawidKossowski**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduced the integration with `MultiRootEditor`. Closes #257.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+					onClick={ () => removeRoot( selectedRoot! ) }
+					disabled={ !selectedRoot }
+				>
+					Remove root
+				</button>
+
+				<select value={ selectedRoot || 'placeholder'} onChange={ ( evt: ChangeEvent<HTMLSelectElement> ) => {
+					setSelectedRoot( evt.target.value );
+				}}>
+					<option hidden value='placeholder'>Select root to remove</option>
```
Comment (Reinmar) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:175]:
```suggestion
					<option hidden value="placeholder">Select root to remove</option>
```

File: src/ckeditor.tsx [hunk 2]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+			const editorData = editor.getFullData();
+			const editorAttributes = editor.getRootsAttributes();
+
+			const { addedKeys: newRoots, removedKeys: removedRoots, modifiedKeys: modifiedRoots } =
+				this.getStateDiff( editorData, nextProps.data || {} );
+			const { addedKeys: newAttributes, removedKeys: removedAttributes, modifiedKeys: modifiedAttributes } =
+				this.getStateDiff( editorAttributes, nextProps.attributes || {} );
+
+			const newRootAttributes = newAttributes.filter( rootAttr =>
+				newRoots.indexOf( rootAttr ) === -1 && nextProps.data[ rootAttr ] !== undefined );
```
Comment (niegowski) [inline src/ckeditor.tsx:389]:
```suggestion
				!newRoots.includes( rootAttr ) && nextProps.data[ rootAttr ] !== undefined );
```

File: src/ckeditor.tsx [hunk 3]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+		if ( roots && 'getFullData' in this.editor! ) {
+			const editor = this.editor as MultiRootEditor;
+
+			const editorData = editor.getFullData();
+			const editorAttributes = editor.getRootsAttributes();
+
+			const { addedKeys: newRoots, removedKeys: removedRoots, modifiedKeys: modifiedRoots } =
+				this.getStateDiff( editorData, nextProps.data || {} );
+			const { addedKeys: newAttributes, removedKeys: removedAttributes, modifiedKeys: modifiedAttributes } =
+				this.getStateDiff( editorAttributes, nextProps.attributes || {} );
```
Comment (niegowski) [inline src/ckeditor.tsx:386]:
```suggestion
			const {
				addedKeys: newRoots,
				removedKeys: removedRoots,
				modifiedKeys: modifiedRoots
			} = this.getStateDiff( editorData, nextProps.data || {} );
			const {
				addedKeys: newAttributes,
				removedKeys: removedAttributes,
				modifiedKeys: modifiedAttributes
			} = this.getStateDiff( editorAttributes, nextProps.attributes || {} );
```

File: src/ckeditor.tsx [hunk 4]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+
+			const newRootAttributes = newAttributes.filter( rootAttr =>
+				newRoots.indexOf( rootAttr ) === -1 && nextProps.data[ rootAttr ] !== undefined );
+			const removedRootAttributes = removedAttributes.filter( rootAttr =>
+				removedRoots.indexOf( rootAttr ) === -1 && nextProps.data[ rootAttr ] !== undefined );
```
Comment (niegowski) [inline src/ckeditor.tsx:391]:
```suggestion
				!removedRoots.includes( rootAttr ) && nextProps.data[ rootAttr ] !== undefined );
```

File: src/ckeditor.tsx [hunk 5]
```diff
@@ -286,13 +425,17 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
 	// Properties definition.
 	public static propTypes = {
 		editor: PropTypes.func.isRequired as unknown as Validator<{ create( ...args: any ): Promise<any> }>,
-		data: PropTypes.string,
+		data: PropTypes.any,
+		attributes: PropTypes.any,
```
Comment (niegowski) [inline src/ckeditor.tsx:429]: Is it possible to narrow this type from `any`?

File: src/ckeditor.tsx [hunk 6]
```diff
@@ -312,16 +455,20 @@ interface Props<TEditor extends Editor> extends InferProps<typeof CKEditor.propT
 	watchdogConfig?: WatchdogConfig;
 	onReady?: ( editor: TEditor ) => void;
 	onError?: ( error: Error, details: ErrorDetails ) => void;
-	onChange?: ( event: EventInfo, editor: TEditor ) => void;
+	onChange?: ( event: EventInfo, editor: TEditor, changedRoots: ChangedRoots ) => void;
 	onFocus?: ( event: EventInfo, editor: TEditor ) => void;
 	onBlur?: ( event: EventInfo, editor: TEditor ) => void;
+	onAddRoot?: ( createElement: () => JSX.Element, attributes: Record<string, unknown> ) => void;
+	onRemoveRoot?: ( root: any ) => void;
```
Comment (niegowski) [inline src/ckeditor.tsx:462]: Can we narrow the type?

File: src/ckeditor.tsx [hunk 7]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
 		} );
 	}
 
+	private getStateDiff( previousState: Record<string, unknown>, newState: Record<string, unknown> ):
+		{ addedKeys: Array<string>; removedKeys: Array<string>; modifiedKeys: Array<string> } {
```
Comment (niegowski) [inline src/ckeditor.tsx:303]:
```suggestion
	private _getStateDiff(
		previousState: Record<string, unknown>, 
		newState: Record<string, unknown>
	): { 
		addedKeys: Array<string>;
		removedKeys: Array<string>;
		modifiedKeys: Array<string>;
	} {
```
For readability and please notice the method name change.

File: src/ckeditor.tsx [hunk 8]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+		const previousStateKeys = Object.keys( previousState );
+		const newStateKeys = Object.keys( newState );
+
+		return {
+			addedKeys: newStateKeys.filter( key => previousStateKeys.indexOf( key ) === -1 ),
+			removedKeys: previousStateKeys.filter( key => newStateKeys.indexOf( key ) === -1 ),
+			modifiedKeys: previousStateKeys.filter( key => newStateKeys.indexOf( key ) !== -1 &&
+				JSON.stringify( previousState[ key ] ) !== JSON.stringify( newState[ key ] ) )
+		};
```
Comment (niegowski) [inline src/ckeditor.tsx:312]:
```suggestion
		return {
			addedKeys: newStateKeys.filter( key => !previousStateKeys.includes( key ) ),
			removedKeys: previousStateKeys.filter( key => !newStateKeys.includes( key ) ),
			modifiedKeys: previousStateKeys.filter( key => (
				newStateKeys.includes( key ) && 
				JSON.stringify( previousState[ key ] ) !== JSON.stringify( newState[ key ] )
			) )
		};
```

File: src/ckeditor.tsx [hunk 9]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+	}
+
+	private _handleRoots = (
```
Comment (niegowski) [inline src/ckeditor.tsx:315]: Why this is not a class method?

File: src/ckeditor.tsx [hunk 10]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+		for ( const modifiedRoot of modifiedRoots ) {
+			if ( editor.data.get( { rootName: modifiedRoot } ) !== nextProps.data[ modifiedRoot ] ) {
+				editor!.data.set( nextProps.data! );
+
+				break;
+			}
+		}
+	};
+
+	private _handleRootsAttributes = (
```
Comment (niegowski) [inline src/ckeditor.tsx:344]: Why this is not a class method?

File: src/ckeditor.tsx [hunk 11]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+
+		removedRoots.forEach( root => {
+			editor.detachRoot( root, true );
+		} );
+
+		for ( const modifiedRoot of modifiedRoots ) {
+			if ( editor.data.get( { rootName: modifiedRoot } ) !== nextProps.data[ modifiedRoot ] ) {
+				editor!.data.set( nextProps.data! );
+
+				break;
```
Comment (niegowski) [inline src/ckeditor.tsx:339]: Please add a code comment explaining why we break the loop.

File: src/ckeditor.tsx [hunk 12]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+			}
+		}
+	};
+
+	private _handleRootsAttributes = (
+		writer: any,
```
Comment (niegowski) [inline src/ckeditor.tsx:345]: Please narrow the types.

File: src/ckeditor.tsx [hunk 13]
```diff
@@ -239,26 +299,105 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+		removedRootsAttributes: Array<string>,
+		modifiedRootsAttributes: Array<string>
+	) => {
+		[ ...newRootsAttributes, ...modifiedRootsAttributes ].forEach( root => {
+			writer.setAttributes( nextProps.attributes[ root ], this.editor!.model.document.getRoot( root ) );
+		} );
+
+		removedRootsAttributes.forEach( root => {
+			writer.clearAttributes( this.editor!.model.document.getRoot( root ) );
+		} );
```
Comment (niegowski) [inline src/ckeditor.tsx:357]: Is this supposed to clear all attributes or remove only some of them?

File: tests/ckeditor.jsx [hunk 14]
```diff
@@ -21,7 +21,7 @@ describe( '<CKEditor> Component', () => {
 	beforeEach( () => {
 		CKEDITOR_VERSION = window.CKEDITOR_VERSION;
 
-		window.CKEDITOR_VERSION = '37.0.0';
+		window.CKEDITOR_VERSION = '38.0.1';
```
Comment (niegowski) [inline tests/ckeditor.jsx:24]: This is changed by mistake or is it really required?

**Review by niegowski — CHANGES_REQUESTED** [review]

File: src/ckeditor.tsx (hunk 9 above)
Comment (DawidKossowski) [reply src/ckeditor.tsx:315]: This is a method of the CKeditor react integration class. Do you mean it should be implemented inside the `MultiRootEditor`?

File: src/ckeditor.tsx [hunk 15]
```diff
@@ -180,9 +183,66 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
 				const viewDocument = editor.editing.view.document;
 
 				modelDocument.on<DocumentChangeEvent>( 'change:data', event => {
+					const changedRoots: ChangedRoots = {};
+
+					modelDocument.differ.getChanges()
+						.forEach( change => {
+							if ( 'position' in change && change.position.root.isAttached() ) {
```
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply src/ckeditor.tsx:190]: As far as I remember attribute change diff items contain only information about changing the state of the root: Attached/Detached. It was useless for me in that place, since I just wanted to get the information on whether the data changed. There is another callback that handles detached roots.

File: src/ckeditor.tsx (hunk 13 above)
Comment (DawidKossowski) [reply src/ckeditor.tsx:357]: It is called only when someone removes the whole key from the attributes object. It's a very rare situation.
@scofalik I remember that we were talking about it. Do you still confirm that we can keep it as it is or maybe you want to rewrite it in some way?

File: src/ckeditor.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (niegowski) [reply src/ckeditor.tsx:190]: I meant the element and text node attributes, like `bold`, `alignment`, `headingRows` etc.

File: src/ckeditor.tsx [hunk 16]
```diff
@@ -239,26 +301,124 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+			) )
+		};
+	}
+
+	private _handleRoots = (
+		nextProps: Props<TEditor>,
+		newRoots: Array<string>,
+		removedRoots: Array<string>,
+		modifiedRoots: Array<string>
+	) => {
```
Comment (niegowski) [inline src/ckeditor.tsx:330]:
```suggestion
	private _handleRoots(
		nextProps: Props<TEditor>,
		newRoots: Array<string>,
		removedRoots: Array<string>,
		modifiedRoots: Array<string>
	) {
```

File: src/ckeditor.tsx [hunk 17]
```diff
@@ -239,26 +301,124 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
+		}
+	};
+
+	private _handleRootsAttributes = (
+		writer: Writer,
+		nextProps: Props<TEditor>,
+		newRootsAttributes: Array<string>,
+		removedRootsAttributes: Array<string>,
+		modifiedRootsAttributes: Array<string>
+	) => {
```
Comment (niegowski) [inline src/ckeditor.tsx:364]:
```suggestion
	private _handleRootsAttributes(
		writer: Writer,
		nextProps: Props<TEditor>,
		newRootsAttributes: Array<string>,
		removedRootsAttributes: Array<string>,
		modifiedRootsAttributes: Array<string>
	) {
```

File: src/ckeditor.tsx (hunk 9 above)
Comment (niegowski) [reply src/ckeditor.tsx:325]: I added a comment with the suggested change: https://github.com/ckeditor/ckeditor5-react/pull/390#discussion_r1258624209

File: src/ckeditor.tsx [hunk 18]
```diff
@@ -191,6 +191,8 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
 								const { rootName } = change.position.root;
 
 								changedRoots[ rootName! ] = { changedData: true };
+							} else {
+								console.log( change );
```
Comment (niegowski) [inline src/ckeditor.tsx:195]:
```suggestion
```

File: src/ckeditor.tsx [hunk 19]
```diff
@@ -422,44 +443,27 @@ export default class CKEditor<TEditor extends Editor> extends React.Component<Pr
...
-		onChange: PropTypes.func,
-		onReady: PropTypes.func,
-		onFocus: PropTypes.func,
-		onBlur: PropTypes.func,
-		onAddRoot: PropTypes.func,
-		onRemoveRoot: PropTypes.func,
-		onError: PropTypes.func,
-		disabled: PropTypes.bool,
-		id: PropTypes.any
-	};
```
Comment (niegowski) [inline src/ckeditor.tsx]: Why you removed the run-time properties validation?

File: src/ckeditor.tsx (hunk 18 above)
Comment (DawidKossowski) [reply src/ckeditor.tsx:195]: Yes... This linter works really bad

File: src/ckeditor.tsx (hunk 19 above)
Comment (DawidKossowski) [reply src/ckeditor.tsx]: For me `prop-types` should be removed since there is almost no value in using it. But okay, I will restore it.

**Comment by oonxt** [comment]
I really need this feature. Is there any progress?

**Comment by scofalik** [comment]
We are getting back to reviewing this integration.

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 20]
```diff
@@ -0,0 +1,286 @@
...
+	const [ content, setContent ] = useState<Record<string, string>>( props.content );
+	const [ attributes, setAttributes ] = useState<Record<string, Record<string, unknown>>>( props.rootsAttributes );
+
+	// The select element state to pick the root for removing.
+	const [ selectedRoot, setSelectedRoot ] = useState<string>();
+
+	// The number of roots that should be added in one row. It is used to present the adding new editor roots feature.
+	const [ numberOfRoots, setNumberOfRoots ] = useState<number>( 1 );
+
+	// The Set of disabled roots. It is used to support read-only feature in multi root editor.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:26]:
```suggestion
	// A set with disabled roots. It is used to support read-only feature in multi root editor.
	// This is for demo purposes and you may remove it in the actual integration or change accordingly to your needs.
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 21]
```diff
@@ -0,0 +1,286 @@
...
+
+		setContent( { ...content, ...newContent } );
+
+		if ( hasNewAttributes ) {
+			setAttributes( { ...editor!.getRootsAttributes() } );
+		}
+	};
+
+	// Function to toggle read-only mode for selected root.
+	const toggleReadOnly = () => {
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:95]: Can we move it so it is next to other read-only-related stuff?

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 22]
```diff
@@ -0,0 +1,286 @@
...
+	const handleNewRoot = ( createRootElement: ( props?: Record<string, unknown> ) => JSX.Element ) => {
+		const element = createRootElement();
+
+		setElements( previousElements => [ ...previousElements, element ] );
+	};
+
+	// Function to handle the removal of a root element from the editor.
+	// This callback is necessary to correctly handle the multi root editor state.
+	const handleRemovedRoot = ( { rootName }: { rootName: string } ) => {
+		// Handling of undo operations.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:164]: This comment tells me nothing.

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 23]
```diff
@@ -0,0 +1,286 @@
...
+	// This callback is necessary to correctly handle the multi root editor state.
+	const handleNewRoot = ( createRootElement: ( props?: Record<string, unknown> ) => JSX.Element ) => {
+		const element = createRootElement();
+
+		setElements( previousElements => [ ...previousElements, element ] );
+	};
+
+	// Function to handle the removal of a root element from the editor.
+	// This callback is necessary to correctly handle the multi root editor state.
+	const handleRemovedRoot = ( { rootName }: { rootName: string } ) => {
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:163]: In the comment, add when it is called. Mention undo and RTC.

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 24]
```diff
@@ -0,0 +1,286 @@
...
+		// Handling of undo operations.
+		if ( content[ rootName ] !== undefined ) {
+			removeRoot( rootName );
+		}
+
+		setElements( previousElements => previousElements.filter( element => element.props.id !== rootName ) );
+	};
+
+	// Grouping elements based on their row attribute and sorting them by order attribute.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:172]:
```suggestion
	// Group elements based on their row attribute and sort them by order attribute.
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 25]
```diff
@@ -0,0 +1,286 @@
...
+	// It is used only for presentation purposes.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:173]:
```suggestion
	// Grouping in a row is used for presentation purposes and you may remove it in actual integration.
	// However, we recommend ordering the roots, so that rows are put in a correct places when undo/redo is used.
	
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 26]
```diff
@@ -0,0 +1,286 @@
...
+	};
+
+	const addRoot = ( newRootAttributes: Record<string, unknown>, rootId?: string ) => {
+		const id = rootId || new Date().getTime();
+
+		for ( let i = 1; i <= numberOfRoots; i++ ) {
+			const rootName = `root-${ i }-${ id }`;
+
+			content[ rootName ] = '';
+			attributes[ rootName ] = { ...newRootAttributes, order: i * 10, row: id };
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:135]:
```suggestion
			// Remove code related to rows if you don't need to handle multiple roots in one row.
			attributes[ rootName ] = { ...newRootAttributes, order: i * 10, row: id };
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 27]
```diff
@@ -0,0 +1,286 @@
...
+				const row = attributes[ element.props.id ].row as string;
+				acc[ row ] = acc[ row ] || [];
+				acc[ row ].push( element );
+
+				return acc;
+			}, {} )
+	);
+
+	return (
+		<>
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:187]: Add comments saying which elements are optional, similar to other comments I've made.

**Review by scofalik — CHANGES_REQUESTED** [review]
These comments are too simple and shallow. I added some suggestions, please improve them.

Also, please go through the code again, and for these functions that are more complex, please consider adding comments also in the body of the function.

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 28]
```diff
@@ -0,0 +1,317 @@
...
+		setSelectedRoot( '' );
+	};
+
+	// Function to handle the addition of a new root element to the editor.
+	//
+	// After adding the editor root the React state (elements, content and attributes) should be updated
+	// to ensure the displayed data up to date.
+	//
+	// Additionally, it is also necessary in real time collaboration where the other user can create a new root.
+	const handleNewRoot = ( createRootElement: ( props?: Record<string, unknown> ) => JSX.Element ) => {
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:174]:
```suggestion
	// Function to handle the addition of a new root element to the editor.
	//
	// After adding an editor root, the React state (elements, content and attributes) should be updated
	// to ensure that the displayed data is up to date.
	//
	// This function is called when a root is created directly (using the editor API),
	// through undo or redo, and during real-time collaboration by a remote user.
	const handleNewRoot = ( createRootElement: ( props?: Record<string, unknown> ) => JSX.Element ) => {
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 29]
```diff
@@ -0,0 +1,317 @@
...
+	};
+
+	// Function to handle the removal of a root element from the editor.
+	//
+	// After removing the editor root the React state (elements, content and attributes) should be updated
+	// to ensure the displayed data up to date.
+	//
+	// Additionally, it is also necessary in real time collaboration where the other user can remove the root.
+	// Added root can be also undone, which will also trigger the removing function and should be handled.
+	const handleRemovedRoot = ( { rootName }: { rootName: string } ) => {
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:187]:
```suggestion
	// Function to handle the removal of a root element from the editor.
	//
	// After removing an editor root, the React state (elements, content and attributes) should be updated
	// to ensure that the displayed data is up to date.
	//
	// This function is called when a root is removed directly (using the editor API),
	// through undo or redo, and during real-time collaboration by a remote user.
	const handleRemovedRoot = ( { rootName }: { rootName: string } ) => {
```

**Comment by scofalik** [comment]
LGTM. Waiting for a green light from QA.

**Comment by glynam1** [comment]
Is there an ETA for this merge? We're awaiting this functionality to test multi root editor

**Comment by scofalik** [comment]
Let me start with openly saying, that it pains us how much this becomes delayed. We know that numerous people are awaiting for this improvement.

We had to delay it again and the ETA is ~16 Nov. We hoped to have this done at the beginning of the month, but we decided to give it more time for following reasons:

1. We discovered some bugs when testing real-time collaboration integration. We managed to fix them, but the integration sample (code) grew too much and it included several hard-to-explain functions that had to be basically copy-pasted into your integration. We didn't like how long and complex the integration became and we wanted to simplify it, move the code from the sample to the component.
2. We received some complaints that we use class-based components, so given the opportunity, we decided to rewrite multi-root integration so that it uses hooks.
3. Finally, we found a bug related setting roots attributes that requires a change in CKE5 engine. We have this fixed and now we are waiting for CKE5 release that is scheduled for 15 Nov. This is why we estimate releasing new React integration with multi-root support to happen on 16 Nov.

**Comment by glynam1** [comment]
> Let me start with openly saying, that it pains us how much this becomes delayed. We know that numerous people are awaiting for this improvement.
> 
> We had to delay it again and the ETA is ~16 Nov. We hoped to have this done at the beginning of the month, but we decided to give it more time for following reasons:
> 
> 1. We discovered some bugs when testing real-time collaboration integration. We managed to fix them, but the integration sample (code) grew too much and it included several hard-to-explain functions that had to be basically copy-pasted into your integration. We didn't like how long and complex the integration became and we wanted to simplify it, move the code from the sample to the component.
> 2. We received some complaints that we use class-based components, so given the opportunity, we decided to rewrite multi-root integration so that it uses hooks.
> 3. Finally, we found a bug related to setting roots attributes. The fix requires a change in CKE5 engine. We have this fixed, and now we are waiting for CKE5 release, which is scheduled for 15 Nov. This is why we estimate releasing new React integration with multi-root support to happen on 16 Nov.

Thanks for the response, getting it this month is great, we will attempt to spin it up when it's merged

File: src/useMultiRootEditor.tsx [hunk 30]
```diff
@@ -0,0 +1,508 @@
...
+	/**
+	 * Returns the editor configuration.
+	 */
+	const _getConfig = (): EditorConfig => {
+		const config = props.config || {};
+
+		if ( props.content && config.initialData ) {
+			console.warn(
+				'Editor data should be provided either using `config.initialData` or `data` properties. ' +
+				'The config property is over the data value and the first one will be used when specified both.'
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:121]:
```suggestion
				'Editor data should be provided either using `config.initialData` or `content` property. ' +
				'The config value takes precedence over `content` property and will be used when both are specified.'
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:1]: You can remove this file.

File: src/useMultiRootEditor.tsx [hunk 31]
```diff
@@ -0,0 +1,508 @@
...
+			// When the component has been remounted it is crucial to wait for removing the old editor
+			// and cleaning the old state.
+			await editorDestructionInProgress.current;
+
+			if ( props.isLayoutReady !== false ) {
+				_initializeEditor();
+			}
+		};
+
+		initEditor();
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:61]: Why declare as separate function if it is used just once? Leftover after refactor?

File: src/useMultiRootEditor.tsx [hunk 32]
```diff
@@ -0,0 +1,508 @@
...
+	 * @param initialContent The initial content.
+	 * @param config CKEditor 5 editor configuration.
+	 */
+	const _createEditor = (
+		initialContent: Record<string, string> | Record<string, HTMLElement>,
+		config: EditorConfig
+	): Promise<MultiRootEditor> => {
+		return props.editor.create( initialContent, config )
+			.then( ( editor: MultiRootEditor ) => {
+				if ( 'disabled' in props ) {
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:255]: Do we have support for this property in other parts of the code? Can I change it and will it change the editor state?

File: src/useMultiRootEditor.tsx [hunk 33]
```diff
@@ -0,0 +1,508 @@
...
+			addedKeys: newAttributes,
+			removedKeys: removedAttributes,
+			modifiedKeys: modifiedAttributes
+		} = _getStateDiff( editorAttributes, attributes || {} );
+
+		const newRootAttributes = newAttributes.filter( rootAttr =>
+			!newRoots.includes( rootAttr ) && attributes[ rootAttr ] !== undefined );
+		const removedRootAttributes = removedAttributes.filter( rootAttr =>
+			!removedRoots.includes( rootAttr ) && attributes[ rootAttr ] !== undefined );
+		const modifiedRootAttributes = modifiedAttributes.filter( rootAttr => attributes[ rootAttr ] !== undefined );
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:400]: Do I get it correctly, that a proper name for `rootAttr` would be `rootName`?

**Review by scofalik — CHANGES_REQUESTED** [review]
Requires a cleanup.

File: demo-react-18/package.json [hunk 34]
```diff
@@ -10,7 +10,7 @@
   },
   "dependencies": {
     "@ckeditor/ckeditor5-react": "file:..",
-    "@ckeditor/ckeditor5-build-classic": "^37.0.0"
+    "@ckeditor/ckeditor5-build-classic": "^38.0.1"
```
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply demo-react-18/package.json:13]: It is dependency in demo app and should not matter.

[the remark this answers is not in the document]
Comment (DawidKossowski) [reply demo-react-18/package.json:13]: Anyway, I can upgrade it to be consistent.

File: src/useMultiRootEditor.tsx (hunk 31 above)
Comment (DawidKossowski) [reply src/useMultiRootEditor.tsx:61]: It is some kind of convention regarding creating async calls in `useEffect` hook. You can read the answer from the main React engineer: https://github.com/facebook/react/issues/14326#issuecomment-441680293

File: src/useMultiRootEditor.tsx (hunk 33 above)
Comment (DawidKossowski) [reply src/useMultiRootEditor.tsx:400]: Yes. Fixed.

File: src/useMultiRootEditor.tsx (hunk 32 above)
Comment (DawidKossowski) [reply src/useMultiRootEditor.tsx:255]: TBH I copied this logic from the "basic" integration. I'm not sure whether we should add something extra here.

Comment (DawidKossowski) [reply src/useMultiRootEditor.tsx:255]: I added additional logic and unit tests.

File: demo-react-18/package.json [hunk 35]
```diff
@@ -10,7 +10,7 @@
   },
   "dependencies": {
     "@ckeditor/ckeditor5-react": "file:..",
-    "@ckeditor/ckeditor5-build-classic": "^37.0.0"
+    "@ckeditor/ckeditor5-build-classic": "^40.1.1"
```
Comment (scofalik) [inline demo-react-18/package.json:13]:
```suggestion
    "@ckeditor/ckeditor5-build-classic": "^40.1.0"
```

File: src/useMultiRootEditor.tsx [hunk 36]
```diff
@@ -0,0 +1,524 @@
...
+		newRootsAttributes: Array<string>,
+		removedRootsAttributes: Array<string>,
+		modifiedRootsAttributes: Array<string>
+	) => {
+		[ ...newRootsAttributes, ...modifiedRootsAttributes ].forEach( root => {
+			Object.keys( attributes![ root ] ).forEach( attr => {
+				editor!.registerRootAttribute( attr );
+			} );
+
+			writer.clearAttributes( editor!.model.document.getRoot( root )! );
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:475]: Can't we simply change the order of handling new&modified attrs with removed attributes instead of preemptively clear all of them?

If not and this line is actually needed to cover some cases, please describe it in a comment.

File: src/useMultiRootEditor.tsx [hunk 37]
```diff
@@ -0,0 +1,524 @@
...
+		const newRootAttributes = newAttributes.filter( rootName =>
+			!newRoots.includes( rootName ) && attributes[ rootName ] !== undefined );
+		const removedRootAttributes = removedAttributes.filter( rootName =>
+			!removedRoots.includes( rootName ) && attributes[ rootName ] === undefined );
+		const modifiedRootAttributes = modifiedAttributes.filter( rootName => attributes[ rootName ] !== undefined );
+
+		editor.model.change( writer => {
+			_handleRoots( newRoots, removedRoots, modifiedRoots );
+			_handleRootsAttributes( writer, newRootAttributes, removedRootAttributes, modifiedRootAttributes );
+		} );
```
Comment (scofalik) [inline src/useMultiRootEditor.tsx:415]: I don't like this part of the integration.

First, every time I get here, I have to re-understand which values mean what. Lack of comments and naming of the variables do not help.

Second, it seems to me that any state where `content` and `attributes` have different keys (different roots) is incorrect. We could check this and throw if that happens.

Third, if a root was added or removed, AFAIR, you don't need to separately add attributes, because you already adding them in `editor.addRoot()` (line 447).

Given that, it doesn't make sense to separately evaluate `newRoots`, `removedRoots`, `newAttributes` and `removedAttributes`. Instead, we should simplify this because there's so many diffs and filtering going on that it is hard to wrap your head about it:

1.  Evaluate which roots were added and which were removed.
2.  Add new roots with attributes.
3.  Detach removed roots.
4.  For the rest, check which changed data. If any, `editor.data.set()`.
5.  As you check if roots data was changed, you can also check if roots attributes changed. If so, re-set the attributes.
    1.  In general, I don't like clear all + set all approach due to extra operations created, but it should not matter much. It shouldn't be many attributes (operations), and it shouldn't trigger any extra actions because differ will "squash" the changes. So I am fine keeping it like this.

Add some inline comments and you will be also able to name variables better as it will be less of them and they will have more precise meaning.

**Comment by scofalik** [comment]
Status update for those waiting for the multi-root React integration.

After another round of QA tests, decided that we weren't ready to release this today. Since we avoid releasing stuff on Fridays, we postponed the release to Monday.

**Review by scofalik — CHANGES_REQUESTED** [review]

File: demo-multiroot-react-18/src/ContextMultiRootEditorDemo.tsx [hunk 38]
```diff
@@ -79,6 +79,9 @@ function ContextEditorDemo(): JSX.Element {
 	return (
 		<>
 			<h2 className="subtitle">Context Multi-root Editor Demo</h2>
+			<p className="info">
+				This sample demonstrates integration with CKEditorContext, ensuring the availability of multiple instances of the Editor.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/ContextMultiRootEditorDemo.tsx:83]:
```suggestion
				This sample demonstrates integration with CKEditorContext.
```

File: demo-multiroot-react-18/src/MultiRootEditorDemo.tsx [hunk 39]
```diff
@@ -22,9 +22,14 @@ export default function MultiRootEditorDemo( props: EditorDemoProps ): JSX.Eleme
 
 	return (
 		<>
-			{ toolbarElement }
+			<h2 className="subtitle">Multi-root Editor Demo</h2>
+			<p className="info">This sample demonstrates the starting point of integration with a multi-root editor in React.</p>
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorDemo.tsx:26]:
```suggestion
			<p className="info">This sample demonstrates the minimal React application that uses multi-root editor integration. You may use it as a starting point for your application.</p>
```

File: demo-multiroot-react-18/src/MultiRootEditorRichDemo.tsx [hunk 40]
```diff
@@ -0,0 +1,211 @@
...
+	return (
+		<>
+			<h2 className="subtitle">Multi-root Editor Demo (rich integration)</h2>
+			<p className="info">
+				This sample demonstrates the more advanced integration of a multi-root editor in React.<br/>
+				There are buttons to add/remove roots in the editor, illustrating how this functionality could be implemented.<br/>
+				Additionally, the &apos;Simulate an error&apos; button is used to trigger an error, causing a restart of the editor
+				by Watchdog. Watchdog can be disabled by passing the `disableWatchdog` flag to the `useMultiRootEditor` hook.<br/>
+				There is also an implementation of the &apos;Toggle read-only&apos; button to demonstrate the functionality of changing
+				the read-only mode for the selected editor root.
```
Comment (scofalik) [inline demo-multiroot-react-18/src/MultiRootEditorRichDemo.tsx:144]:
```suggestion
				This sample demonstrates a more advanced integration of the multi-root editor in React.<br/>
				Multiple extra features were implemented to illustrate how you can customize your application and use the provided API.<br/>
				They are optional, and you do not need to include them in your application. However, they can be a good starting point for your own custom features.<br/>
				The "Simulate an error" button makes the editor throw an error to show you how it is restarted by the `Watchdog` mechanism. Note, that this mechanism is available by default and you don't need to write additional code to use it. It can be disabled by passing the `disableWatchdog` flag to the `useMultiRootEditor` hook.
```

**Review by scofalik — APPROVED** [review]

File: src/useMultiRootEditor.tsx [hunk 41]
```diff
@@ -176,22 +172,16 @@ const useMultiRootEditor = ( props: MultiRootHookProps ): MultiRootHookReturns =
...
 
 		if ( Object.keys( newAttributes ).length ) {
 			setAttributes( previousAttributes => ( { ...previousAttributes, ...newAttributes } ) );
-
-			shouldUpdateEditor.current = false;
 		}
 
 		/* istanbul ignore else */
-		if ( props.onChange && !shouldUpdateEditor.current ) {
+		if ( props.onChange ) {
```
[the remark this answers is not in the document]
Comment (scofalik) [reply src/useMultiRootEditor.tsx:182]: We talked F2F and they are situations where it could lead to incorrect results.
